% GENLATEXFORPLOTS Generate a Latex snippet for embedding in the summary
% report.
%
% Yaguang Zhang, Purdue, 07/12/2017

clear; clc; close all;

%% Configurations

% The absolute path to the shared Google Drive folder "Annapolis
% Measurement Campaign". Please make sure it is correct for the machine
% which will run this script.
%     On Mac Lemma: '/Users/zhan1472/Google Drive/Annapolis Measurement
%      Campaign';
%  On Windows Dell: '\\LEMMA\Google Drive\Annapolis Measurement Campaign';
ABS_PATH_TO_EARS_SHARED_FOLDER = ...
    '\\LEMMA\Google Drive\Annapolis Measurement Campaign';

% Configure other paths accordingly.
ABS_PATH_TO_DATA = fullfile(ABS_PATH_TO_EARS_SHARED_FOLDER, 'Data');
ABS_PATH_TO_SAVE_SNIPPET = fullfile(ABS_PATH_TO_EARS_SHARED_FOLDER, ...
    'PostProcessingResults', 'SummaryReport');
ABS_PATH_TO_PLOTS = fullfile(ABS_PATH_TO_EARS_SHARED_FOLDER, ...
    'PostProcessingResults', 'SummaryReport', 'plots');

%% Before Generating the Snippet

disp(' ------------------ ')
disp('  genLatexForPlots')
disp(' ------------------ ')

% Add libs to current path.
cd(fileparts(mfilename('fullpath')));
addpath(fullfile(pwd));
cd('..'); setPath;

% The plots should already be there.
assert(exist(ABS_PATH_TO_PLOTS, 'dir')==7, ...
    'No plots were found! Please run genPlots first.');


% Load the plot information generated by genPlots.
disp(' ')
disp('    Loading information for the plots...')
% allSeriesParentDirs and allSeriesDirs will be available after this.
load(fullfile(ABS_PATH_TO_SAVE_PLOTS, 'plotInfo.mat'));
disp('    Done!')

%% Generate the Snippet Site by Site

disp(' ')
disp('  => Generating Latex snippet for plots...')

% For each day and a specific type of measurements (e.g. LargeScale, SIMO
% and Conti).
for idxPar=1:length(allSeriesParentDirs)
    disp([num2str(idxPar), '/', num2str(length(allSeriesParentDirs))])
    
    % Note that depending on the machine where genPlots was excuted, the
    % exact paths to the plots may change, so we will only use the folder
    % names.
    [~, curParFolderName] = fileparts(allSeriesParentDirs(idxPar).name);
    
    % Find all photos for the measurement sites.
    
    % Find the GPS on map figure.
    
    % Find the signal over time plots.
    
    % Generate the Latex snippet.
end
disp('     Done!')

% EOF